---
- name: Postpone firmware upgrade for MX networks via Meraki API
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ./group_vars/merakivault.yml
  vars:
    meraki_org_id: 977108
    meraki_base_url: "https://api.meraki.com/api/v1"

  tasks:

    - name: Validate Meraki API access
      uri:
        url: "{{ meraki_base_url }}/organizations"
        method: GET
        headers:
          X-Cisco-Meraki-API-Key: "{{ vault_meraki_apikey }}"
        return_content: yes
      register: org_check
      failed_when: org_check.status != 200

    - name: Confirm organization exists
      assert:
        that: meraki_org_id | int in (org_check.json | map(attribute='id') | map('int') | list)
        fail_msg: "Org {{ meraki_org_id }} not found"

    - name: Compute postponement time
      set_fact:
        postpone_time: "{{ lookup('pipe', 'date -u -d \"+30 days\" +%Y-%m-%dT%H:%M:%SZ') }}"

    - name: Initialize pagination
      set_fact:
        all_devices: []
        starting_after: ""

    - name: Fetch all devices (pagination loop)
      uri:
        url: >-
          {{ meraki_base_url }}/organizations/{{ meraki_org_id }}/devices?perPage=300
          {{ '&startingAfter=' + starting_after if starting_after else '' }}
        method: GET
        headers:
          X-Cisco-Meraki-API-Key: "{{ vault_meraki_apikey }}"
        return_content: yes
      register: page
      failed_when: page.status != 200
      loop: "{{ range(0, 100) | list }}"
      loop_control:
        label: "Page {{ loop.index }}"
      until: page.json is defined and page.json | length == 0
      retries: 3
      delay: 2

    - name: Build full device list
      set_fact:
        all_devices: "{{ all_devices + item.json }}"
        starting_after: "{{ item.json[-1].serial }}"
      loop: "{{ page.results }}"
      when: item.json is defined and item.json | length > 0

    - name: Debug total devices
      debug:
        msg: "Fetched {{ all_devices | length }} devices"

    - name: Extract MX network IDs
      set_fact:
        mx_network_ids: >-
          {{ all_devices | selectattr('model', 'search', '^MX') | map(attribute='networkId') | unique | list }}

    - name: Get firmware info
      uri:
        url: "{{ meraki_base_url }}/networks/{{ item }}/firmwareUpgrades"
        method: GET
        headers:
          X-Cisco-Meraki-API-Key: "{{ vault_meraki_apikey }}"
        return_content: yes
      register: fw_info
      loop: "{{ mx_network_ids }}"
      failed_when: false

    - name: Postpone upgrade (dry-run)
      uri:
        url: "{{ meraki_base_url }}/networks/{{ item }}/firmwareUpgrades"
        method: PUT
        headers:
          X-Cisco-Meraki-API-Key: "{{ vault_meraki_apikey }}"
        body_format: json
        body:
          products:
            appliance:
              nextUpgrade:
                time: "{{ postpone_time }}"
                toVersion:
                  id: "{{ fw_info.results[loop.index0].json.products.appliance.nextUpgrade.toVersion.id }}"
              participateInNextBetaRelease: false
      loop: "{{ mx_network_ids }}"
      when: >
        fw_info.results[loop.index0].status == 200 and
        fw_info.results[loop.index0].json.products.appliance.nextUpgrade is defined
      check_mode: yes